### ISSUE TITLE
Yarn build fails with [ERR_UNSUPPORTED_ESM_URL_SCHEME]:  in windows

### ISSUE THREAD

**Issue by san-sankar** [microsoft/showwhy#320]
The build is failing on the below error on 
OS windows 11 , 
Node 16.14.2
Yarn 3.2.4

@showwhy/discover-app:assets: explore workers bundled!
@showwhy/webapp:assets: cache miss, executing 48d45a860ef8ac5c
@showwhy/webapp:build: cache miss, executing d9e4fc173ef26bc4
@showwhy/webapp:build:     ✔ check types (10156.50ms)
@showwhy/webapp:build: error running webpack build Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
@showwhy/webapp:build:     at new NodeError (node:internal/errors:371:5)
@showwhy/webapp:build:     at throwIfUnsupportedURLProtocol (node:internal/modules/esm/resolve:1035:11)
@showwhy/webapp:build:     at defaultResolve (node:internal/modules/esm/resolve:1105:3)
@showwhy/webapp:build:     at resolve$1 (file:///C:/softwares/tools/causal/showwhy-main/showwhy-main/.pnp.loader.mjs:1963:14)
@showwhy/webapp:build:     at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
@showwhy/webapp:build:     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
@showwhy/webapp:build:     at ESMLoader.import (node:internal/modules/esm/loader:332:22)
@showwhy/webapp:build:     at importModuleDynamically (node:internal/modules/esm/translators:106:35)
@showwhy/webapp:build:     at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
@showwhy/webapp:build:     at getConfig (file:///C:/softwares/tools/causal/showwhy-main/showwhy-main/.yarn/__virtual__/@essex-scripts-virtual-f4c528482d/0/cache/@essex-scripts-npm-22.2.0-4e53cad6af-03aa5393a1.zip/node_modules/@essex/scripts/lib/steps/webpack/getConfig.mjs:24:24) {
@showwhy/webapp:build:   code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
@showwhy/webapp:build: }
@showwhy/webapp:build: 🔥 bundle
@showwhy/webapp:build: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
@showwhy/webapp:build:     at new NodeError (node:internal/errors:371:5)
@showwhy/webapp:build:     at throwIfUnsupportedURLProtocol (node:internal/modules/esm/resolve:1035:11)
@showwhy/webapp:build:     at defaultResolve (node:internal/modules/esm/resolve:1105:3)
@showwhy/webapp:build:     at resolve$1 (file:///C:/softwares/tools/causal/showwhy-main/showwhy-main/.pnp.loader.mjs:1963:14)
@showwhy/webapp:build:     at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
@showwhy/webapp:build:     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
@showwhy/webapp:build:     at ESMLoader.import (node:internal/modules/esm/loader:332:22)
@showwhy/webapp:build:     at importModuleDynamically (node:internal/modules/esm/translators:106:35)
@showwhy/webapp:build:     at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
@showwhy/webapp:build:     at getConfig (file:///C:/softwares/tools/causal/showwhy-main/showwhy-main/.yarn/__virtual__/@essex-scripts-virtual-f4c528482d/0/cache/@essex-scripts-npm-22.2.0-4e53cad6af-03aa5393a1.zip/node_modules/@essex/scripts/lib/steps/webpack/getConfig.mjs:24:24) {
@showwhy/webapp:build:   code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
@showwhy/webapp:build: }

**Comment by dayesouza** [comment]
Hi @san-sankar, we're currently using [WSL ](https://learn.microsoft.com/en-us/windows/wsl/install), could you test with that while we verify why isn't it working on windows?

**Comment by san-sankar** [comment]
Hi @dayesouza  i will install WSL , test and get back to you.
