### ISSUE TITLE
showwhy Deployment Errors

### ISSUE THREAD

**Issue by ArunIntellipaat** [microsoft/showwhy#436]
yarn install and yarn build is not getting executed.
[ShowWhy Deployment Errors.docx](https://github.com/microsoft/showwhy/files/13652061/ShowWhy.Deployment.Errors.docx)

**Comment by dayesouza** [comment]
Hi! Did you tried again? If so, can you paste here the content of the log file that follows the the exit code 1?

**Comment by ArunIntellipaat** [comment]
Hi Dayenne,

Once after getting that error I did not try again.

Please find the complete error log file attached for your reference.


Thanks & Regards,
Arun K S

**Comment by dayesouza** [comment]
At the end of the yarn install there's a log file about it (/tmp/xxxx/build.log), can you check for that please? Also, try again because it might be just a network error at that time

![image](https://github.com/microsoft/showwhy/assets/16024923/fd7a9ad5-9192-4259-b9d4-bb1111846ca4)

**Comment by ArunIntellipaat** [comment]
Hi Dayenne,

Thank you for investing your time in helping me to sort the ShowWhy
deployment issue.

Please find the build.log file data for your reference.

# This file contains the result of Yarn building a package ***@***.***:11.0.0)
# Script name: postinstall

/home/arun/showwhy/showwhy/.yarn/unplugged/rome-npm-11.0.0-22ed7a887e/node_modules/rome/scripts/postinstall.js:18
const binName = PLATFORMS?.[platform]?.[arch];
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js
(internal/modules/cjs/loader.js:1027:10)
    at Object.require$$0.Module._extensions..js
(/home/arun/showwhy/showwhy/.pnp.cjs:45996:33)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.require$$0.Module._load
(/home/arun/showwhy/showwhy/.pnp.cjs:45815:22)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:188:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

[image: image.png]


Regards,
Arun K S

**Comment by ArunIntellipaat** [comment]
Hi Dayenne,

Hope all is well with you.

Did you get a chance to review the error log details and find any solution?

I am looking forward to have the showwhy deployed on my console.

Thanks in advance,


Regards,
Arun K S

**Comment by dayesouza** [comment]
Hi Arun, I couldn't reproduce the error. Which version of node and yarn are you using?

**Comment by ArunIntellipaat** [comment]
Dayenne,

Good to hear that you were able to execute the showwhy deployment.

I just followed the steps as instructed in the github repo -
showwhy/docs/deployment/LOCAL_DEPLOY.md
at main · microsoft/showwhy (github.com)
<https://github.com/microsoft/showwhy/blob/main/docs/deployment/LOCAL_DEPLOY.md>
.

It will be great if you can share the execution steps so that I can perform
the same as it is very critical and urgent for us to get it deployed please.

**Comment by dayesouza** [comment]
I am using WSL 2 in my windows machine. I have docker installed on my windows and integrated with WSL.

I install minikube in my WSL like this:
`curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64`
`sudo install minikube-linux-amd64 /usr/local/bin/minikube`

then

`minikube start`
`minikube addons enable ingress`
`eval $(minikube docker-env)`

then `yarn install`


If for some reason it still don't work for you, I verified that the Deployment on Azure is working fine, so if you'd like to test you can even [create a test account for free](https://azure.microsoft.com/en-us/free/search/?ef_id=_k_324d0252fad011cb889f67d6c766a851_k_&OCID=AIDcmmzmnb0182_SEM__k_324d0252fad011cb889f67d6c766a851_k_&msclkid=324d0252fad011cb889f67d6c766a851) and [deploy it with our instructions](https://github.com/microsoft/showwhy?tab=readme-ov-file#deployment)

**Comment by ArunIntellipaat** [comment]
Dayenne,

Can you please verify and let me know if the showwhy deployment on AWS
works fine?

**Comment by dayesouza** [comment]
My take is that you can try to create it the same way you do in your local machine but in a Virtual Machine on AWS, since the error you're getting I couldn't reproduce and I could guess that it might be something on your machine...
The way we do in our azure deployment is azure only since the built containers are in there

**Comment by ArunIntellipaat** [comment]
Understood Dayenne!

So, you basically work only on the Azure platform and have not tried on
AWS. So, not sure if it works there right?
